import { createContext, useContext, useState } from "react";
import { AlertTriangle, Bell, CheckCircle2, CloudOff, FileText, RefreshCw, Route as RouteIcon, Search, Truck, Wifi, X, Zap } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";

type NetworkState = "online" | "offline" | "limited";
const labels: Record<NetworkState, [string, string]> = { online: ["Online", "All services connected"], offline: ["Offline", "Working in offline mode"], limited: ["Limited Connectivity", "Some services may be delayed"] };
const NetworkContext = createContext<{ status: NetworkState; setStatus: (x: NetworkState) => void; sync: () => void; pending: number }>({ status: "online", setStatus: () => {}, sync: () => {}, pending: 28 });
export function NetworkProvider({ children }: { children: React.ReactNode }) { const [status, setStatus] = useState<NetworkState>("online"); const [pending, setPending] = useState(28); const sync = () => { if (status !== "offline") setPending(0); }; return <NetworkContext.Provider value={{ status, setStatus, sync, pending }}>{children}</NetworkContext.Provider> }
export function useNetwork() { return useContext(NetworkContext); }
function StatusIcon({ status }: { status: NetworkState }) { return status === "online" ? <Wifi size={14} /> : status === "offline" ? <CloudOff size={14} /> : <AlertTriangle size={14} /> }
export function NetworkStatus() { const { status, setStatus, pending } = useNetwork(); const [open, setOpen] = useState(false); return <div className="network-status-wrap"><button className={`network-status ${status}`} onClick={() => setOpen(!open)}><StatusIcon status={status} /><span><b>{labels[status][0]}</b><small>{labels[status][1]}</small></span><i /></button>{open && <div className="network-popover"><div className="network-pop-head"><strong>Network Status</strong><button onClick={() => setOpen(false)}><X size={14} /></button></div><div className="network-selector">{(["online", "limited", "offline"] as NetworkState[]).map(x => <button className={status === x ? "active" : ""} key={x} onClick={() => setStatus(x)}><StatusIcon status={x} />{labels[x][0]}</button>)}</div><div className="network-details"><span>Last Successful Sync <b>Today, 10:42 AM</b></span><span>Pending Actions <b>{pending}</b></span><span>Pending Reports <b>3</b></span><span>Pending Location Updates <b>18</b></span></div></div>}</div> }
export function SyncCenter({ close }: { close: () => void }) { const { status, sync, pending } = useNetwork(); const [running, setRunning] = useState(false); const [done, setDone] = useState(false); const start = () => { if (status === "offline") return; setRunning(true); setTimeout(() => { sync(); setRunning(false); setDone(true); }, 1500); }; return <div className="modal-backdrop"><div className="sync-modal"><button className="modal-close" onClick={close}><X size={18} /></button><span className="eyebrow blue">FIELD OPERATIONS</span><h2>Data Synchronization</h2>{done ? <div className="sync-complete"><CheckCircle2 size={34} /><strong>Synchronization Complete</strong><p>28 items synchronized successfully.</p><small>Last Synced: Just now</small></div> : <><p className="modal-subtitle">Review locally stored actions before sending them to connected services.</p><div className="sync-categories">{[["Incident Reports", "3 Pending"], ["Vehicle GPS Updates", "18 Pending"], ["Route Actions", "5 Pending"], ["Alert Acknowledgements", "0 Completed"], ["Field Photos", "2 Pending"], ["AI Decision Logs", "0 Completed"]].map(x => <div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>{running && <div className="sync-progress"><RefreshCw size={14} className="spin" /> Synchronizing browser-stored field data...</div>}<div className="modal-footer"><span>{pending} items pending</span><button className="primary-button" disabled={running || status === "offline"} onClick={start}>{running ? "Synchronizing..." : "Sync Now"} <RefreshCw size={14} /></button></div></>}</div></div> }
export function OfflineBanner() { const { status, pending } = useNetwork(); const [dismissed, setDismissed] = useState(false); if (status === "online" || dismissed) return null; return <div className={`offline-banner ${status}`}><StatusIcon status={status} /><div><strong>{status === "offline" ? "Offline Web Mode" : "Limited Connectivity"}</strong><p>{status === "offline" ? "Your connection is currently unavailable. You can continue recording field reports and operational updates. They will synchronize when connectivity is restored." : "Some services may be delayed while the connection stabilizes."}</p></div><span>{pending} pending</span><button onClick={() => setDismissed(true)} aria-label="Dismiss offline banner"><X size={14} /></button></div> }
export function GlobalFieldTools() { const navigate = useNavigate(); const { pending } = useNetwork(); const [syncOpen, setSyncOpen] = useState(false); const [menu, setMenu] = useState(false); const [search, setSearch] = useState(""); const [searchOpen, setSearchOpen] = useState(false); const results = [{ id: "NER-TRK-1042", label: "Vehicle tracking", to: "/vehicles", icon: Truck }, { id: "INC-2026-0187", label: "Critical incident", to: "/incidents", icon: AlertTriangle }, { id: "Guwahati → Itanagar", label: "Route intelligence", to: "/routes", icon: RouteIcon }, { id: "Bhalukpong Risk Zone", label: "Risk intelligence", to: "/risk-intelligence", icon: AlertTriangle }, { id: "Critical Route Alert", label: "Alert center", to: "/alerts", icon: Bell }].filter(x => !search || x.id.toLowerCase().includes(search.toLowerCase())); return <><span className="demo-mode-badge">Demo Mode</span><OfflineBanner /><div className="global-tools"><div className="global-search-wrap">{searchOpen && <div className="global-search-panel"><label><Search size={15} /><input autoFocus value={search} onChange={e => setSearch(e.target.value)} placeholder="Search vehicles, routes, incidents, alerts..." /></label>{search && results.map(r => <button key={r.id} onClick={() => navigate(r.to)}><r.icon size={14} /><span><strong>{r.id}</strong><small>{r.label}</small></span></button>)}</div>}<button className="global-tool-button" onClick={() => setSearchOpen(!searchOpen)} aria-label="Global search"><Search size={17} /></button></div><NetworkStatus /><button className="global-tool-button" onClick={() => setSyncOpen(true)} aria-label="Open synchronization center"><RefreshCw size={17} />{pending > 0 && <b>{pending}</b>}</button><button className="global-tool-button" onClick={() => setMenu(!menu)} aria-label="Open quick actions"><Zap size={17} /></button>{menu && <div className="quick-actions"><strong>Quick Actions</strong>{[["Report Incident", "/incidents", AlertTriangle], ["Analyze Route", "/routes", RouteIcon], ["Track Vehicle", "/vehicles", Truck], ["View Critical Alerts", "/alerts", Bell], ["Open AI Command Center", "/ai-command-center", Zap]].map(([x,to,Icon]: any) => <Link to={to} key={x} onClick={() => setMenu(false)}><Icon size={14} />{x}</Link>)}</div>}</div>{syncOpen && <SyncCenter close={() => setSyncOpen(false)} />}</> }
export function LoadingSkeleton({ lines = 3 }: { lines?: number }) { return <div className="loading-skeleton" aria-label="Loading"><i /><i /><i className={lines > 3 ? "wide" : ""} /></div> }
export function EmptyState({ title, message, action }: { title: string; message: string; action?: string }) { return <div className="empty-state"><FileText size={24} /><strong>{title}</strong><p>{message}</p>{action && <button className="outline-button">{action}</button>}</div> }
export function ErrorState({ retry }: { retry?: () => void }) { return <div className="empty-state error-state"><AlertTriangle size={24} /><strong>Unable to Load Data</strong><p>Some data could not be loaded. Check your connection and try again.</p><div><button className="primary-button" onClick={retry}>Retry</button><button className="outline-button">Continue Offline</button></div></div> }
